name: pyhomogenize
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bokeh=2.3.0
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cftime=1.4.1
  - click=7.1.2
  - cloudpickle=1.6.0
  - curl=7.75.0
  - cytoolz=0.11.0
  - dask=2021.3.0
  - dask-core=2021.3.0
  - distributed=2021.3.0
  - freetype=2.10.4
  - fsspec=0.8.7
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - jinja2=2.11.3
  - jpeg=9d
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.75.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - msgpack-python=1.0.2
  - ncurses=6.2
  - netcdf4=1.5.6
  - numpy=1.20.1
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.3
  - partd=1.1.0
  - pillow=8.1.2
  - pip=21.0.1
  - psutil=5.8.0
  - pyparsing=2.4.7
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.0
  - setuptools=49.6.0
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.34.0
  - tblib=1.6.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - wheel=0.36.2
  - xarray=0.17.0
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - iteration-utilities==0.11.0

