name: pyhomogenize-tests
channels:
    - conda-forge
    - nodefaults
dependencies:
    - dask
    - xarray
    - numpy
    - setuptools
    - pooch
    - netCDF4
    - iteration_utilities
    # for testing
    - pytest
    - pytest-cov
    - pytest-env
